	IFND	DEVICES_BOOTBLOCK_I
DEVICES_BOOTBLOCK_I	=	1
	RSRESET
BB		RS.B	0
BB_ID		RS.B	4
BB_CHKSUM	RS.L	1
BB_DOSBLOCK	RS.L	1
BB_ENTRY	RS.W	0
BB_SIZE		RS.W	0
BOOTSECTS	=	2
BBID_DOS	MACRO
	DC.B	'DOS',0
	ENDM
BBID_KICK	MACRO
	DC.B	'KICK'
	ENDM
BBNAME_DOS	=	[['D'<<24]!['O'<<16]!['S'<<8]]
BBNAME_KICK	=	[['K'<<24]!['I'<<16]!['C'<<8]!['K']]
	ENDC
