	IFND	DEVICES_TIMER_I
DEVICES_TIMER_I	=	1
	IFND	EXEC_IO_I
	INCLUDE	exec/io.i
	ENDC
UNIT_MICROHZ	=	0
UNIT_VBLANK	=	1
TIMERNAME	MACRO
	DC.B	'timer.device',0
	DS.W	0
	ENDM
	RSRESET
TIMEVAL		RS.B	0
TV_SECS		RS.L	1
TV_MICRO	RS.L	1
TV_SIZE		RS.W	0
	RSRESET
TIMEREQUEST	RS.B	IO_SIZE
IOTV_TIME	RS.B	TV_SIZE
IOTV_SIZE	RS.W	0
	DEVINIT
	DEVCMD	TR_ADDREQUEST
	DEVCMD	TR_GETSYSTIME
	DEVCMD	TR_SETSYSTIME
	ENDC
