	IFND	EXEC_DEVICES_I
EXEC_DEVICES_I	=	1
	IFND	EXEC_LIBRARIES_I
	INCLUDE	exec/libraries.i
	ENDC
	IFND	EXEC_PORTS_I
	INCLUDE	exec/ports.i
	ENDC
	RSRESET
DD	RS.B	LIB_SIZE
DD_SIZE	RS.W	0
	RSRESET
UNIT	RS.B	MP_SIZE
UNIT_FLAGS	RS.B	1
UNIT_pad	RS.B	1
UNIT_OPENCNT	RS.W	1
UNIT_SIZE	RS.W	0
UNITB_ACTIVE	=	0
UNITF_ACTIVE	=	1<<0
UNITB_INTASK	=	1
UNITF_INTASK	=	1<<1
	ENDC
