	IFND	EXEC_INTERRUPTS_I
EXEC_INTERRUPTS_I	=	1
	IFND	EXEC_NODES_I
	INCLUDE	exec/nodes.i
	ENDC
	IFND	EXEC_LISTS_I
	INCLUDE	exec/lists.i
	ENDC
	RSRESET
IS	RS.B	LN_SIZE
IS_DATA	RS.L	1
IS_CODE	RS.L	1
IS_SIZE	RS.W	0
	RSRESET
IV	RS.B	0
IV_DATA	RS.L	1
IV_CODE	RS.L	1
IV_NODE	RS.L	1
IV_SIZE	RS.W	0
SB_SAR	=	15
SF_SAR	=	1<<15
SB_TQE	=	14
SF_TQE	=	1<<14
SB_SINT	=	13
SF_SINT	=	1<<13
	RSRESET
SH	RS.B	LH_SIZE
SH_PAD	RS.W	1
SH_SIZE	RS.W	0
SIH_PRIMASK	=	$0F0
SIH_QUEUES	=	5
INTB_NMI	=	15
INTF_NMI	=	1<<15
	ENDC
