	IFND	EXEC_NODES_I
EXEC_NODES_I	=	1
	RSRESET
LN	RS.B	0
LN_SUCC	RS.L	1
LN_PRED	RS.L	1
LN_TYPE	RS.B	1
LN_PRI	RS.B	1
LN_NAME	RS.L	1
LN_SIZE	RS.W	0
	RSRESET
MLN		RS.B	0
MLN_SUCC	RS.L	1
MLN_PRED	RS.L	1
MLN_SIZE	RS.W	0
NT_UNKNOWN	=	0
NT_TASK		=	1
NT_INTERRUPT	=	2
NT_DEVICE	=	3
NT_MSGPORT	=	4
NT_MESSAGE	=	5
NT_FREEMSG	=	6
NT_REPLYMSG	=	7
NT_RESOURCE	=	8
NT_LIBRARY	=	9
NT_MEMORY	=	10
NT_SOFTINT	=	11
NT_FONT		=	12
NT_PROCESS	=	13
NT_SEMAPHORE	=	14
NT_SIGNALSEM	=	15
	ENDC
