	IFND	EXEC_RESIDENT_I
EXEC_RESIDENT_I	=	1
	RSRESET
RT		RS.B	0
RT_MATCHWORD	RS.W	1
RT_MATCHTAG	RS.L	1
RT_ENDSKIP	RS.L	1
RT_FLAGS	RS.B	1
RT_VERSION	RS.B	1
RT_TYPE		RS.B	1
RT_PRI		RS.B	1
RT_NAME		RS.L	1
RT_IDSTRING	RS.L	1
RT_INIT		RS.L	1
RT_SIZE		RS.W	0
RTC_MATCHWORD	=	$4AFC
RTB_COLDSTART	=	0
RTF_COLDSTART	=	1<<0
RTB_AUTOINIT	=	7
RTF_AUTOINIT	=	1<<7
RTM_WHEN	=	1
RTW_NEVER	=	0
RTW_COLDSTART	=	1
	ENDC
