	IFND	EXEC_SEMAPHORES_I
EXEC_SEMAPHORES_I	=	1
	IFND	EXEC_NODES_I
	INCLUDE	exec/nodes.i
	ENDC
	IFND	EXEC_LISTS_I
	INCLUDE	exec/lists.i
	ENDC
	IFND	EXEC_PORTS_I
	INCLUDE	exec/ports.i
	ENDC
	RSRESET
SM		RS.B	MP_SIZE
SM_BIDS		RS.W	1
SM_SIZE		RS.W	0
SM_LOCKMSG	=	MP_SIGTASK
	RSRESET
SSR		RS.B	MLN_SIZE
SSR_WAITER	RS.L	1
SSR_SIZE	RS.W	0
	RSRESET
SS		RS.B	LN_SIZE
SS_NESTCOUNT	RS.W	1
SS_WAITQUEUE	RS.B	MLH_SIZE
SS_MULTIPLELINK	RS.B	SSR_SIZE
SS_OWNER	RS.L	1
SS_QUEUECOUNT	RS.W	1
SS_SIZE		RS.W	0
	ENDC
