	IFND	RESOURCES_MISC_I
RESOURCES_MISC_I	=	1
	IFND	EXEC_TYPES_I
	INCLUDE	exec/types.i
	ENDC
	IFND	EXEC_LIBRARIES_I
	INCLUDE	exec/libraries.i
	ENDC
MR_SERIALPORT	=	0
MR_SERIALBITS	=	1
MR_PARALLELPORT	=	2
MR_PARALLELBITS	=	3
NUMMRTYPES	=	4
	RSRESET
MiscResource	RS.B	LIB_SIZE
mr_AllocArray	RS.B	4*NUMMRTYPES
mr_Sizeof	RS.W	0
	LIBINIT	LIB_BASE
	LIBDEF	MR_ALLOCMISCRESOURCE
	LIBDEF	MR_FREEMISCRESOURCE
MISCNAME	MACRO
	DC.B	'misc.resource',0
	ENDM
	ENDC
