	IFND	DEVICES_SCSIDISK_I
DEVICES_SCSIDISK_I	EQU	1
HD_SCSICMD	EQU	28
	STRUCTURE	SCSICmd,0
	APTR	scsi_Data
	ULONG	scsi_Length
	ULONG	scsi_Actual
	APTR	scsi_Command
	UWORD	scsi_CmdLength
	UWORD	scsi_CmdActual
	UBYTE	scsi_Flags
	UBYTE	scsi_Status
	LABEL	scsi_SIZEOF
SCSIF_WRITE	EQU	0
SCSIF_READ	EQU	1
HFERR_SelfUnit	EQU	40
HFERR_DMA	EQU	41
HFERR_Phase	EQU	42
HFERR_Parity	EQU	43
HFERR_SelTimeout	EQU	44
HFERR_BadStatus	EQU	45
HFERR_NoBoard	EQU	50
	ENDC
